version: '3.3'
services:
    mapper:
        build: mapper-image
        volumes:
            - ./input:/input
            - ./output:/output
            - ./mapper-config:/config
        command: java -jar /mapper-image/RMLMapper.jar -v -m /config/mapping.rml.ttl -o /output/output.ttl
